import { create } from 'zustand'

const themeConfig = {
  'fresh-forest': {
    pageBg: 'bg-green-100',
    checkInBox: 'bg-green-500',
    checkInBoxHover: 'hover:bg-green-600',
    checkInBoxBorder: 'border border-green-700',
    nonCheckInBox: 'bg-slate-700',
    navbarBgGradient: 'bg-gradient-to-r from-green-300 via-green-200 to-green-300',
    fontColor: 'text-slate-800',
    navFontColor: 'text-slate-800',
    button: 'bg-green-600 hover:bg-green-700',
  },
  'mustard-dusk': {
    pageBg: 'bg-yellow-100',
    checkInBox: 'bg-yellow-300',
    checkInBoxHover: 'hover:bg-yellow-400',
    checkInBoxBorder: 'border border-yellow-400',
    nonCheckInBox: 'bg-stone-400',
    navbarBgGradient: 'bg-gradient-to-r from-yellow-800 via-yellow-900 to-yellow-800',
    fontColor: 'text-slate-900',
    navFontColor: 'text-yellow-200',
    button: 'bg-yellow-500 hover:bg-yellow-600 text-slate-800',
  },
  'citrus-sky': {
    pageBg: 'bg-blue-50',
    checkInBox: 'bg-orange-400',
    checkInBoxHover: 'hover:bg-orange-500',
    checkInBoxBorder: 'border border-orange-600',
    nonCheckInBox: 'bg-blue-200',
    navbarBgGradient: 'bg-gradient-to-r from-blue-800 via-blue-900 to-blue-800',
    fontColor: 'text-slate-900',
    navFontColor: 'text-orange-100',
    button: 'bg-orange-500 hover:bg-orange-600',
  },
  'rose-night': {
    pageBg: 'bg-gray-950',
    checkInBox: 'bg-rose-400',
    checkInBoxHover: 'hover:bg-rose-500',
    checkInBoxBorder: 'border border-rose-600',
    nonCheckInBox: 'bg-gray-700',
    navbarBgGradient: 'bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900',
    fontColor: 'text-rose-100',
    navFontColor: 'text-rose-200',
    button: 'bg-rose-500 hover:bg-rose-600 text-white',
  },
  'sky-violet': {
    pageBg: 'bg-sky-100',
    checkInBox: 'bg-indigo-400',
    checkInBoxHover: 'hover:bg-indigo-500',
    checkInBoxBorder: 'border border-indigo-500',
    nonCheckInBox: 'bg-sky-300',
    navbarBgGradient: 'bg-gradient-to-r from-indigo-700 via-sky-600 to-indigo-700',
    fontColor: 'text-slate-900',
    navFontColor: 'text-indigo-100',
    button: 'bg-indigo-500 hover:bg-indigo-600 text-white',
  },
  'aqua-mint': {
    pageBg: 'bg-teal-100',
    checkInBox: 'bg-emerald-400',
    checkInBoxHover: 'hover:bg-emerald-500',
    checkInBoxBorder: 'border border-emerald-500',
    nonCheckInBox: 'bg-teal-300',
    navbarBgGradient: 'bg-gradient-to-r from-teal-700 via-emerald-600 to-teal-700',
    fontColor: 'text-slate-900',
    navFontColor: 'text-emerald-100',
    button: 'bg-emerald-500 hover:bg-emerald-600 text-white',
  },
  'midnight-purple': {
    pageBg: 'bg-zinc-900',
    checkInBox: 'bg-purple-500',
    checkInBoxHover: 'hover:bg-purple-600',
    checkInBoxBorder: 'border border-purple-500',
    nonCheckInBox: 'bg-zinc-700',
    navbarBgGradient: 'bg-gradient-to-r from-purple-800 via-zinc-800 to-purple-800',
    fontColor: 'text-purple-100',
    navFontColor: 'text-purple-200',
    button: 'bg-purple-500 hover:bg-purple-600 text-white',
  },
  'peachy-sunset': {
    pageBg: 'bg-orange-50',
    checkInBox: 'bg-rose-300',
    checkInBoxHover: 'hover:bg-rose-400',
    checkInBoxBorder: 'border border-rose-400',
    nonCheckInBox: 'bg-orange-200',
    navbarBgGradient: 'bg-gradient-to-r from-pink-400 via-orange-300 to-pink-400',
    fontColor: 'text-slate-800',
    navFontColor: 'text-rose-100',
    button: 'bg-rose-400 hover:bg-rose-500 text-white',
  },
}

const useThemeStore = create((set) => ({
  theme: 'fresh-forest',
  themeConfig,
  setTheme: (theme) => set({ theme }),
}));

export default useThemeStore;